### ISSUE TITLE
[Bug] Home page groups - Link not working

### ISSUE THREAD

**Issue by demenech** [datopian/birmingham-city-observatory#10]
## Description
The links from the groups on the homepage are not working. It redirects the user to the search page with the query on the URL, but the results are now showing up initially.
![ss-2022-09-09-09:14:27](https://user-images.githubusercontent.com/16550934/189347759-e7fd7a9b-4345-4b79-9199-ec6c419dad45.png)
![ss-2022-09-09-09:15:48](https://user-images.githubusercontent.com/16550934/189347956-c30d906a-a925-4306-894b-1a8f9fabcb99.png)

## Acceptance Criteria
- [ ] The issue is fixed

## Tasks
- [x] Investigate and fix the issue

**Comment by juanbrits** [comment]
Group links are working.
