### ISSUE TITLE
[Bug] Resource preview is not loading

### ISSUE THREAD

**Issue by demenech** [datopian/birmingham-city-observatory#12]
## Description
There's a preview button on the Resource page. It's currently outputting an error, not matter the format of the resource:
![ss-2022-09-09-09:24:40](https://user-images.githubusercontent.com/16550934/189349284-f5e5baee-e5a4-47cd-a3b6-d0c497e94882.png)

Example resource:
/@department-of-finance/population-of-birmingham/r/1b3f00b6-6dbe-4317-970d-8640a7d7ad3b

**Comment by demenech** [comment]
@anuveyatsu this is a similar error to the one I pinged you earlier today.
The resource exists in CKAN, it has the correct id, but when trying to fetch it with datastore_search it doesn't find it.
Also, the preview won't load in CKAN itself.
Do you have any suggestion on what could be happening?

Edit: some resources load in CKAN.

**Comment by anuveyatsu** [comment]
@demenech the resource you linked is not throwing an error: https://birmingham-city-observatory.vercel.app/@department-of-finance/population-of-birmingham/r/1b3f00b6-6dbe-4317-970d-8640a7d7ad3b

**Comment by anuveyatsu** [comment]
but generally, I'd inspect the browser network for debugging, e.g., what's the response from DataStore API. If it's 404, it means the resource wasn't pushed to DataStore etc.

**Comment by demenech** [comment]
@anuveyatsu thanks for your reply. Indeed it's not displaying the error message, but the request is still failing:
![ss-2022-09-16-07:56:40](https://user-images.githubusercontent.com/16550934/190624785-eee715c2-05ae-429b-b4cd-a49d7c3db191.png)

**Comment by demenech** [comment]
@joyisi fixed this, @juanbrits . Should be working as expected now.

**Comment by juanbrits** [comment]
@joyisi please note that this solution is not working across all datasets. Please can you assist?

![image](https://user-images.githubusercontent.com/103997912/194538232-ea81d892-96a5-43cc-8944-d36e4c77b946.png)

**Comment by juanbrits** [comment]
@demenech please do not forget that the URL on the resource page is incorrect. The ID seen below should be a human readable name:

birmingham-city-observatory.vercel.app/@birmingham-city-council/indices-of-deprivation-2019/r/**543a12ff-d674-4621-b04b-d227d0cea789**

**Comment by demenech** [comment]
@juanbrits PR: https://github.com/datopian/portal-birmingham-city-observatory/pull/48

**Comment by juanbrits** [comment]
Link to resource where Preview Is not Available:

https://birmingham-city-observatory.vercel.app/@birmingham-city-council/indices-of-deprivation-2019/r/IMD%202019%20-%20LSOA

https://birmingham-city-observatory.vercel.app/@birmingham-city-council/indices-of-deprivation-2019/r/IMD%202019%20Birmingham%20LA%20Summary

**Comment by juanbrits** [comment]
@lucasmbispo sharing this issue with the Tech Help team.

**Comment by juanbrits** [comment]
Preview is available.

**Comment by juanbrits** [comment]
The download of the following resource works fine: https://birmingham-city-observatory.vercel.app/@birmingham-city-council/secondary-school-admissions-intake-2013

However when you look at the resource information table on the side, the size is N/A and there is no preview available?
I tried looking for column names longer than 64 chars but no avail.

**Comment by juanbrits** [comment]
This sheet contains contains data about the resources that are not previewable. https://docs.google.com/spreadsheets/d/1fkjbMBa85zXEkkhpcXpluYdnQg_l7Q4maFbrTZrG3wY/edit#gid=35657302
