### ISSUE TITLE
Change layout of Home Page Heading

### ISSUE THREAD

**Issue by demenech** [datopian/birmingham-city-observatory#16]
## Acceptance Criteria
- [ ] I can see the new layout of the home page heading 

## Tasks
- [x] Change layout of Home Page Heading from “Open Data Birmingham City Observatory” to
Birmingham City Observatory (first line), Open Data (second line), Thousands of datasets with guaranteed updates(third line)

**Comment by demenech** [comment]
Results:
![ss-2022-09-12-13:20:43](https://user-images.githubusercontent.com/16550934/189705531-6e55efcc-ff47-4f67-a295-111c82c9efe2.png)

**Comment by juanbrits** [comment]
@demenech  please look at the alignment of the search bar with the new headings. It seems a bit off to me?

![image](https://user-images.githubusercontent.com/103997912/190966863-c38919c9-be2e-4163-97d7-c6973c4e6bca.png)

**Comment by demenech** [comment]
@juanbrits thanks noticing that, I will fix it later in the day

**Comment by demenech** [comment]
Pushed a change for this

**Comment by juanbrits** [comment]
Resolved.
