### ISSUE TITLE
MyBrum map to feature in showcases: 

### ISSUE THREAD

**Issue by juanbrits** [datopian/birmingham-city-observatory#19]
The client would like to see their My Brum Map feature in Showcases: 
https://maps.birmingham.gov.uk/webapps/brum/mybrummap/  

### Acceptance Criteria

- [x] The map can be accessed via Showcases

### Tasks

- [x] Investigate how to embed

**Comment by lucasmbispo** [comment]
Showcases extension implemented in the portal.
