### ISSUE TITLE
Implement Showcases

### ISSUE THREAD

**Issue by juanbrits** [datopian/birmingham-city-observatory#23]
### Tasks

- [x] #19 
- [x] Implement text to be sent from client

**Comment by juanbrits** [comment]
@juanbrits to request from the client if they would like to add any other links to other sites through showcases

**Comment by juanbrits** [comment]
@lucasmbispo as discussed with the client today - the MyBrum map should be a link to a new page where the map is viewed in full screen.  What I am thinking is to create a show case box like on ODNI that directs the user to a new tab of the map when clicked?
![image](https://user-images.githubusercontent.com/103997912/191240359-7699902a-bb4e-4347-9ec1-f8e214c7bdd1.png)

**Comment by lucasmbispo** [comment]
Requested team advice on showcases plugin.

**Comment by lucasmbispo** [comment]
Showcases extension added to the portal.
