### ISSUE TITLE
Implement Footer

### ISSUE THREAD

**Issue by juanbrits** [datopian/birmingham-city-observatory#25]
### Job Story
As a user I would like to see quick links to relevant pages from the footer. 

### Acceptance Criteria

- [ ] All links are directing to their intended URLs

### Tasks

- [x] About - use https://data.birmingham.gov.uk/about as reference

**Comment by demenech** [comment]
My suggestion:
![ss-2022-09-20-10:11:53](https://user-images.githubusercontent.com/16550934/191266885-318a1a49-4b6a-4c69-b0b1-0c306d15fd00.png)
@juanbrits

**Comment by demenech** [comment]
or, even better: let's put `terms and conditions` under the first column and get rid of the last column (please note that the previous PR is not yet merged)

**Comment by demenech** [comment]
![ss-2022-09-20-10:15:48](https://user-images.githubusercontent.com/16550934/191267635-9ad285a0-5f21-45aa-b404-003903160e06.png)

**Comment by demenech** [comment]
I'm creating the about and terms and conditions pages with the content from the Data Factory

**Comment by juanbrits** [comment]
Footer has been implemented.
