### ISSUE TITLE
Add a banner to the new site

### ISSUE THREAD

**Issue by juanbrits** [datopian/birmingham-city-observatory#26]
It is going to be a separate landing page from the page. 

It should read: Thanks for coming to the new Birmingham City Observatory. We are currently upgrading the old site, and the new platform will be re-launched as by November 2022. 

Include a countdown timer and a coming soon animation if possible.

**Comment by juanbrits** [comment]
@lucasmbispo please confirm the status of this?

**Comment by juanbrits** [comment]
I don't get the Banner when I open the portal?

**Comment by lucasmbispo** [comment]
The banner is allocated at the url https://birmingham-city-observatory.vercel.app/landing
