### ISSUE TITLE
Icon error when selected

### ISSUE THREAD

**Issue by jagdeep-matharu** [datopian/birmingham-city-observatory#30]
Error message "Application error: a client-side exception has occurred (see the browser console for more information)" appears when clicking icons within the carousel. Screenshot below attached. 

![image](https://user-images.githubusercontent.com/114396473/192245200-1cbc4f0a-e606-4c2b-b864-8c51349a6b26.png)

**Comment by demenech** [comment]
Fixed

**Comment by juanbrits** [comment]
We are able to click on the icons and be redirected to a filtered dataset page
