### ISSUE TITLE
Investigate DATA API button not behaving

### ISSUE THREAD

**Issue by juanbrits** [datopian/birmingham-city-observatory#36]
As a user when I click the data API button, it currently does not behave as expected. It should behave as other data API buttons. 

The button should expose resources so that you can interact with the resources. In this instance it should download data.

**Comment by juanbrits** [comment]
@lucasmbispo this is still outstanding. Please update.

**Comment by juanbrits** [comment]
@lucasmbispo please note that as per Anu the DATA API button should be implemented. It should lead to instructions on how to use the Data API.

**Comment by lucasmbispo** [comment]
Fixed in preview https://birmingham-city-observatory-66qz1sths-datopian1.vercel.app/
PR: https://github.com/datopian/portal-birmingham-city-observatory/pull/55
