### ISSUE TITLE
Bug - Resources Not Downloading

### ISSUE THREAD

**Issue by juanbrits** [datopian/birmingham-city-observatory#37]
The download of many of the resources is not working. When an user tries to download the resources, it shows a 404 page.
Examples:
https://birmingham-city-observatory.vercel.app/@birmingham-city-council/february-2022-payments-to-suppliers
https://birmingham-city-observatory.vercel.app/@birmingham-city-council/february-2022-purchase-card-transactions

Using an automated script it was generated a list of the resources available in the portal, in which one of the fields indicate if the resource is presenting the download issue or not:
[results.csv](https://github.com/datopian/birmingham-city-observatory/files/9767328/results.csv)

It looks like it's not working for all the Excel resources, as well as for some resources in other formats.

# Acceptance Criteria
- [ ] The download functionality is working for all the resources

# Tasks
- [x] Investigate the bug
- [x] Implement a fix

**Comment by juanbrits** [comment]
@demenech please will you populate the issue with all relevent information and tag @joyisi as soon as done for her assistance.

**Comment by demenech** [comment]
@juanbrits @joyisi I hope that's clear

**Comment by juanbrits** [comment]
At last glance only 5 datasets remained that were not downloadable.

**Comment by juanbrits** [comment]
@demenech please can you confirm if we can close this issue?
Does your script show any resources that we can't download?

**Comment by demenech** [comment]
@juanbrits I'm rerunning it

**Comment by demenech** [comment]
@juanbrits
There are still 5 resources: https://docs.google.com/spreadsheets/d/1fkjbMBa85zXEkkhpcXpluYdnQg_l7Q4maFbrTZrG3wY/edit#gid=35657302
I think we can ask the client to reupload these and see if that helps.

**Comment by juanbrits** [comment]
There are still 2 resources that are not downloadable. However these 2 resources were not available on the old Birmingham Data Factory either. 

England IOD Education Sub Domain 2010
Birmingham IOD Barriers to Housing Sub Domains 2010
