### ISSUE TITLE
The number of downloads on a resource shows 6100+

### ISSUE THREAD

**Issue by Daniellappv** [datopian/birmingham-city-observatory#39]
## Acceptance

* [x] Remove the number of downloads from the search page (the public doesn't need to see this number)

**Comment by demenech** [comment]
**PR**: https://github.com/datopian/portal-birmingham-city-observatory/pull/64
**Preview**: https://birmingham-city-observatory-git-improvements-2023-02-datopian1.vercel.app/

**Comment by anuveyatsu** [comment]
FIXED.
