### ISSUE TITLE
Resource description is blank

### ISSUE THREAD

**Issue by Daniellappv** [datopian/birmingham-city-observatory#41]
## Context

Resource description appears blank even after adding description in the admin backend. 

<img width="320" alt="Screenshot 2023-02-23 at 11 47 28" src="https://user-images.githubusercontent.com/45828069/220884239-8e7e98bd-9db2-4406-83c0-aeabf6be4c24.png">

(not the best screenshot but you can see that there's nothing under **Resource description** while he had added a description to that resource already and it should've been visible there)

## Acceptance

* [x] Resource description appears in the frontend

**Comment by anuveyatsu** [comment]
@demenech I'd recommend first checking if that's actually true. From what I've seen, it is working.

**Comment by demenech** [comment]
@anuveyatsu @Daniellappv 
It seems to be working:
![image](https://user-images.githubusercontent.com/16550934/220888919-56285058-9768-424d-b673-a14f3a018dd3.png)

I remember working on this, here's the commit: https://github.com/datopian/portal-birmingham-city-observatory/commit/9bfa5de56ba13b732d279fef289e0825ea06bbc2

**Comment by anuveyatsu** [comment]
FIXED:

<img width="1440" alt="Screen Shot 2023-09-12 at 4 53 24 PM" src="https://github.com/datopian/birmingham-city-observatory/assets/17809581/0c71ff34-c2fe-4fd3-9251-149d21f070c2">
