### ISSUE TITLE
Remove the whole “Interesting Insights” section (the charts / graphs) from the homepage

### ISSUE THREAD

**Issue by Daniellappv** [datopian/birmingham-city-observatory#42]
## Context

There is a bug related to some of the charts / graphs in this section currently and some of them aren't getting displayed. Instead of re-loading them, the clients asked us to just get rid of the whole interesting insights section

<img width="760" alt="Screenshot 2023-02-23 at 11 50 36" src="https://user-images.githubusercontent.com/45828069/220884971-41af685d-2999-4e10-a4ea-d015d84966f8.png">

## Acceptance

* [x] Remove the interesting insights from the homepage

**Comment by demenech** [comment]
**PR**: https://github.com/datopian/portal-birmingham-city-observatory/pull/64
**Preview**: https://birmingham-city-observatory-git-improvements-2023-02-datopian1.vercel.app/

**Comment by anuveyatsu** [comment]
FIXED:

<img width="1440" alt="Screen Shot 2023-09-12 at 4 54 04 PM" src="https://github.com/datopian/birmingham-city-observatory/assets/17809581/318d7217-8ba7-4725-9c1f-17b1addc85ab">
