### ISSUE TITLE
Link to dataset on the insights page

### ISSUE THREAD

**Issue by Daniellappv** [datopian/birmingham-city-observatory#43]
Currently, on the [insights page](https://www.cityobservatory.birmingham.gov.uk/insights), hovering over the insight and over the eg. "1 dataset" redirects us to the insight only _(it's all on the same link)_.

What we want is to be able to go to the insight when clicking on the insight title but to go to the actual dataset when clicking on “1 dataset”.

(see [showcases](https://birmingham-city-observatory.datopian.com/showcase))

<img width="380" alt="Screenshot 2023-02-23 at 12 46 05" src="https://user-images.githubusercontent.com/45828069/220885479-889e0e4f-8591-4458-9bad-d4824b790ac7.png">

## Acceptance

* [x] Two separate links for the insight and the dataset that relates to the insight

**Comment by demenech** [comment]
**Note:** we can have multiple datasets associated with a showcase:
![image](https://user-images.githubusercontent.com/16550934/220918663-a171230f-7f1d-4e81-8a1e-d237134919ef.png)
We'd have to create or adapt a page to list all the datasets associated with a showcase. For now, it's redirecting to the first dataset.

**Comment by demenech** [comment]
**PR**: https://github.com/datopian/portal-birmingham-city-observatory/pull/64
**Preview**: https://birmingham-city-observatory-git-improvements-2023-02-datopian1.vercel.app/

**Comment by anuveyatsu** [comment]
FIXED.
