### ISSUE TITLE
Fix search result card's org info

### ISSUE THREAD

**Issue by anuveyatsu** [datopian/birmingham-city-observatory#47]
Currently it shows wrong icon and unnecessary information of dataset name:

<img width="942" alt="Screenshot 2024-03-09 at 11 31 24 AM" src="https://github.com/datopian/birmingham-city-observatory/assets/17809581/1d7bb5c6-be31-4760-b473-887468a8a879">

## Tasks

- [ ] Update icon to something that represents organisation.
- [ ] Remove `/ {dataset-name}`

**Comment by RonaldojCampos** [comment]
created pull request 
https://github.com/datopian/portal-birmingham-city-observatory/pull/74

**Comment by RonaldojCampos** [comment]
merged
