### ISSUE TITLE
Share open source icons

### ISSUE THREAD

**Issue by anuveyatsu** [datopian/birmingham-city-observatory#7]
## Tasks

- [x] Add a list of open source icon libraries to consider for the project.

**Comment by anuveyatsu** [comment]
Hi @ZoeWright below is a list of open source icons libraries that we could use:

- Our default icons: https://heroicons.com/
- Here we have more than just icons: https://iconscout.com/
- Fontawesome: https://fontawesome.com/

**Comment by ZoeWright** [comment]
[icons for categories final.docx](https://github.com/datopian/birmingham-city-observatory/files/9490734/icons.for.categories.final.docx)
Icons and categories list. I've provided the category for them, a screenshot, and a direct link to the icon in the attached word document. Any problems, let me know.
